export interface GuestEntry {
  id: string;
  timestamp: string;
  name: string;
  institution: string; // Instansi/Asal
  phone: string;
  purpose: string;
  photoUrl: string | null; // Base64 string
  signatureUrl: string | null; // Base64 string
  aiSummary?: string; // Generated by Gemini
  aiCategory?: string; // Generated by Gemini
}

export enum ViewState {
  HOME = 'HOME',
  FORM = 'FORM',
  LIST = 'LIST',
  ABOUT = 'ABOUT'
}